# Pre-commit hooks configuration
# Install with: `pipx install pre-commit` or `pip install pre-commit`
# Enable with: `pre-commit install`

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.7
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format

